export const mockRooms = [
  {
    id: "room-richmond-consulting",
    host_id: "host-bridge-practice",
    title: "Quiet consulting room on Bridge Road",
    slug: "richmond-consulting-bridge-road",
    suburb: "Richmond",
    state: "VIC",
    price_per_day_cents: 14000,
    room_type: "talk_therapy",
    available_days: ["mon", "wed", "fri"],
    amenities: ["soundproofing", "waiting_room", "wifi", "kitchen"],
    image_urls: [],
    description:
      "A still, well-lit room in an established psychology practice. Suitable for 50-minute sessions, with a small shared waiting area and tea point.",
    is_published: true,
    created_at: "2026-08-20T09:00:00.000Z",
    host: {
      id: "host-bridge-practice",
      practice_name: "Bridge Practice",
      contact_email: "hello+richmond-1@alliedrooms.example",
      phone: "03 9000 1101",
      website_url: null,
      created_at: "2026-07-01T00:00:00.000Z",
    },
  },
  {
    id: "room-richmond-treatment",
    host_id: "host-yarrabend-osteo",
    title: "Treatment room with plinth, Swan Street",
    slug: "richmond-treatment-swan-street",
    suburb: "Richmond",
    state: "VIC",
    price_per_day_cents: 16000,
    room_type: "bodywork",
    available_days: ["tue", "thu", "sat"],
    amenities: ["plinth", "parking", "wifi", "wheelchair"],
    image_urls: [],
    description:
      "Ground-floor osteopathy clinic with a hydraulic plinth, basin, and street-level access. Easy tram stop and a handful of clinic car parks.",
    is_published: true,
    created_at: "2026-08-18T09:00:00.000Z",
    host: {
      id: "host-yarrabend-osteo",
      practice_name: "Yarra Bend Osteo",
      contact_email: "hello+richmond-2@alliedrooms.example",
      phone: "03 9000 1102",
      website_url: null,
      created_at: "2026-07-02T00:00:00.000Z",
    },
  },
  {
    id: "room-southyarra-loft",
    host_id: "host-chapel-rooms",
    title: "Upstairs talk-therapy suite near Chapel Street",
    slug: "south-yarra-talk-chapel",
    suburb: "South Yarra",
    state: "VIC",
    price_per_day_cents: 18000,
    room_type: "talk_therapy",
    available_days: ["mon", "tue", "wed", "thu"],
    amenities: ["soundproofing", "waiting_room", "wifi", "hicaps"],
    image_urls: [],
    description:
      "Soft-furnished consulting suite above a mixed allied-health floor. HICAPS at reception on weekdays. Best for psychologists and counsellors.",
    is_published: true,
    created_at: "2026-08-22T09:00:00.000Z",
    host: {
      id: "host-chapel-rooms",
      practice_name: "Chapel Street Rooms",
      contact_email: "hello+southyarra-1@alliedrooms.example",
      phone: "03 9000 1201",
      website_url: null,
      created_at: "2026-07-03T00:00:00.000Z",
    },
  },
  {
    id: "room-southyarra-medical",
    host_id: "host-toorak-rd-clinic",
    title: "Medical consult room on Toorak Road",
    slug: "south-yarra-medical-toorak-rd",
    suburb: "South Yarra",
    state: "VIC",
    price_per_day_cents: 22000,
    room_type: "medical",
    available_days: ["wed", "thu", "fri"],
    amenities: ["hicaps", "waiting_room", "parking", "wifi", "wheelchair"],
    image_urls: [],
    description:
      "Clinical consult room in a GP-led building. Handwash, examination couch, and shared nurse station by arrangement. Weekday afternoons preferred.",
    is_published: true,
    created_at: "2026-08-12T09:00:00.000Z",
    host: {
      id: "host-toorak-rd-clinic",
      practice_name: "Toorak Road Clinic",
      contact_email: "hello+southyarra-2@alliedrooms.example",
      phone: "03 9000 1202",
      website_url: null,
      created_at: "2026-07-04T00:00:00.000Z",
    },
  },
  {
    id: "room-fitzroy-gertrude",
    host_id: "host-gertrude-collective",
    title: "North-facing room on Gertrude Street",
    slug: "fitzroy-consulting-gertrude",
    suburb: "Fitzroy",
    state: "VIC",
    price_per_day_cents: 12000,
    room_type: "talk_therapy",
    available_days: ["mon", "wed", "thu", "fri"],
    amenities: ["soundproofing", "wifi", "kitchen"],
    image_urls: [],
    description:
      "Compact consulting room in a converted terrace. High windows, thick walls, and a kettle in the hall. Suited to independent psychologists.",
    is_published: true,
    created_at: "2026-08-24T09:00:00.000Z",
    host: {
      id: "host-gertrude-collective",
      practice_name: "Gertrude Collective",
      contact_email: "hello+fitzroy-1@alliedrooms.example",
      phone: "03 9000 1301",
      website_url: null,
      created_at: "2026-07-05T00:00:00.000Z",
    },
  },
  {
    id: "room-fitzroy-bodywork",
    host_id: "host-smith-st-health",
    title: "Bodywork studio off Smith Street",
    slug: "fitzroy-bodywork-smith-street",
    suburb: "Fitzroy",
    state: "VIC",
    price_per_day_cents: 11000,
    room_type: "bodywork",
    available_days: ["tue", "wed", "sat"],
    amenities: ["plinth", "wifi", "kitchen"],
    image_urls: [],
    description:
      "Timber-floor treatment space with a fixed plinth and linen store. Shared bathroom. Good for myotherapy, remedial massage, or osteo overflow days.",
    is_published: true,
    created_at: "2026-08-16T09:00:00.000Z",
    host: {
      id: "host-smith-st-health",
      practice_name: "Smith Street Health",
      contact_email: "hello+fitzroy-2@alliedrooms.example",
      phone: "03 9000 1302",
      website_url: null,
      created_at: "2026-07-06T00:00:00.000Z",
    },
  },
  {
    id: "room-hawthorn-glenferrie",
    host_id: "host-glenferrie-rooms",
    title: "Consulting room near Glenferrie Station",
    slug: "hawthorn-consulting-glenferrie",
    suburb: "Hawthorn",
    state: "VIC",
    price_per_day_cents: 15000,
    room_type: "talk_therapy",
    available_days: ["mon", "tue", "thu", "fri"],
    amenities: ["waiting_room", "wifi", "parking", "hicaps"],
    image_urls: [],
    description:
      "Second-floor room in a long-running allied health practice. Lift access, street parking after 10am, and a receptionist on weekdays.",
    is_published: true,
    created_at: "2026-08-21T09:00:00.000Z",
    host: {
      id: "host-glenferrie-rooms",
      practice_name: "Glenferrie Rooms",
      contact_email: "hello+hawthorn-1@alliedrooms.example",
      phone: "03 9000 1401",
      website_url: null,
      created_at: "2026-07-07T00:00:00.000Z",
    },
  },
  {
    id: "room-brunswick-sydney-rd",
    host_id: "host-sydney-rd-osteo",
    title: "Sessional treatment room on Sydney Road",
    slug: "brunswick-treatment-sydney-road",
    suburb: "Brunswick",
    state: "VIC",
    price_per_day_cents: 9500,
    room_type: "bodywork",
    available_days: ["wed", "fri", "sat"],
    amenities: ["plinth", "wifi", "wheelchair"],
    image_urls: [],
    description:
      "Bright, no-frills treatment room with a plinth and basin. Tram at the door. A practical overflow day for physio or osteo lists.",
    is_published: true,
    created_at: "2026-08-25T09:00:00.000Z",
    host: {
      id: "host-sydney-rd-osteo",
      practice_name: "Sydney Road Osteo",
      contact_email: "hello+brunswick-1@alliedrooms.example",
      phone: "03 9000 1501",
      website_url: null,
      created_at: "2026-07-08T00:00:00.000Z",
    },
  },
];
