export const mockRooms = [
  {
    id: "r1",
    host_id: "h1",
    title: "Light-Filled Soundproofed Psych Suite",
    slug: "light-filled-soundproofed-psych-suite-richmond",
    suburb: "Richmond",
    state: "VIC",
    postcode: "3121",
    price_per_day_cents: 13000,
    room_type: "talk_therapy",
    available_days: ["mon", "wed", "fri"],
    amenities: ["soundproofing", "waiting_room", "wifi", "kitchen"],
    description:
      "Quiet, acoustic-insulated consulting space ideal for psychotherapy or counselling. Features warm timber accents, natural light, and access to a shared practitioner lounge.",
    image_urls: [],
    is_published: true,
    created_at: "2026-08-20T09:00:00.000Z",
    host: {
      id: "h1",
      practice_name: "Richmond Wellness Collective",
      contact_email: "hello@richmondwellness.example.com",
      phone: "03 9000 1122",
      website_url: "https://richmondwellness.example.com",
      created_at: "2026-07-01T00:00:00.000Z",
    },
  },
  {
    id: "r2",
    host_id: "h2",
    title: "Allied Health Room with Electric Plinth",
    slug: "allied-health-room-electric-plinth-south-yarra",
    suburb: "South Yarra",
    state: "VIC",
    postcode: "3141",
    price_per_day_cents: 15500,
    room_type: "bodywork",
    available_days: ["tue", "thu", "sat"],
    amenities: ["plinth", "hicaps", "parking", "wifi"],
    description:
      "Equipped for osteopaths, physios, or myotherapists. High-low electric treatment table, hand basin, and reception meet-and-greet support included.",
    image_urls: [],
    is_published: true,
    created_at: "2026-08-18T09:00:00.000Z",
    host: {
      id: "h2",
      practice_name: "South Yarra Health Group",
      contact_email: "admin@syhealth.example.com",
      phone: "03 9888 4433",
      website_url: "https://syhealth.example.com",
      created_at: "2026-07-02T00:00:00.000Z",
    },
  },
  {
    id: "r3",
    host_id: "h3",
    title: "Heritage Therapy Space near Brunswick St",
    slug: "heritage-therapy-space-fitzroy",
    suburb: "Fitzroy",
    state: "VIC",
    postcode: "3065",
    price_per_day_cents: 12000,
    room_type: "talk_therapy",
    available_days: ["mon", "tue", "thu"],
    amenities: ["soundproofing", "waiting_room", "wifi"],
    description:
      "Character-filled room in high-ceiling heritage building. Private, calm atmosphere for talking therapies and dietetics.",
    image_urls: [],
    is_published: true,
    created_at: "2026-08-22T09:00:00.000Z",
    host: {
      id: "h3",
      practice_name: "Fitzroy Practice Rooms",
      contact_email: "rooms@fitzroypractice.example.com",
      phone: "03 9411 0099",
      website_url: null,
      created_at: "2026-07-03T00:00:00.000Z",
    },
  },
  {
    id: "r4",
    host_id: "h4",
    title: "Medical & Specialist Consulting Suite",
    slug: "medical-specialist-consulting-suite-hawthorn",
    suburb: "Hawthorn",
    state: "VIC",
    postcode: "3122",
    price_per_day_cents: 18000,
    room_type: "medical",
    available_days: ["wed", "thu", "fri"],
    amenities: ["wheelchair", "hicaps", "parking", "waiting_room"],
    description:
      "Full clinical setup with examination couch, doctor's desk, ground-floor wheelchair accessibility, and dedicated patient parking.",
    image_urls: [],
    is_published: true,
    created_at: "2026-08-12T09:00:00.000Z",
    host: {
      id: "h4",
      practice_name: "Hawthorn Medical Precinct",
      contact_email: "reception@hawthornmed.example.com",
      phone: "03 9819 7000",
      website_url: "https://hawthornmed.example.com",
      created_at: "2026-07-04T00:00:00.000Z",
    },
  },
  {
    id: "r5",
    host_id: "h5",
    title: "Minimalist Multi-Disciplinary Studio",
    slug: "minimalist-multi-disciplinary-studio-brunswick",
    suburb: "Brunswick",
    state: "VIC",
    postcode: "3056",
    price_per_day_cents: 11000,
    room_type: "talk_therapy",
    available_days: ["mon", "wed", "sat"],
    amenities: ["wifi", "kitchen", "waiting_room"],
    description:
      "Sunlit room with flexible furniture arrangements. Suitable for solo practitioners looking for an affordable, creative neighbourhood setting.",
    image_urls: [],
    is_published: true,
    created_at: "2026-08-24T09:00:00.000Z",
    host: {
      id: "h5",
      practice_name: "Brunswick Health Hub",
      contact_email: "contact@brunswickhub.example.com",
      phone: null,
      website_url: null,
      created_at: "2026-07-05T00:00:00.000Z",
    },
  },
];
